server:
  port: 8083
  servlet:
    context-path: /business/division-management/v1
  error:
    include-message: always
    include-binding-errors: always

spring:
  main:
    allow-bean-definition-overriding: true
    lazy_initializatieon: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/db_diviac
    username: postgres
    password: ${POSTGRES_PASS:securePassword123.}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    auto-commit: true
    maximum-pool-size: 100
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    validation-query: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pe.com.gob.diviac.business.division.adapter.output.mybatis.alias

feign:
  client:
    config:
      support-audit-api:
        base-url: http://${SUPPORT_AUDIT_API_HOST:localhost}:${SUPPORT_AUDIT_API_PORT:9090}/support/audit-producer-management/v1/producers
        connectTimeout: 25000
        readTimeout: 30000
        writeTimeout: 25000
        loggerLevel: basic

